[package]
name = "openssl-sys2"
version = "0.1.0"
license = "MIT"
authors = ["Arnav Singh <arsing@microsoft.com>"]
edition = "2018"
build = "build/main.rs"

[dependencies]
openssl-sys = "0.9"

[build-dependencies]
openssl-build = { path = "../openssl-build/" }
