name: CI

on: [push]

jobs:
  openssl_100:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run
      run: ./ci/run.sh
      env:
        OPENSSL_DEVEL_PACKAGE_NAME: 'libopenssl-1_0_0-devel'

  openssl_110:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run
      run: ./ci/run.sh
      env:
        OPENSSL_DEVEL_PACKAGE_NAME: 'libopenssl-1_1-devel'
